// Generado por web_i18n/i18n_rebuild.js (en) a partir de web/js/epocas_fichas.js. No editar a mano: editar la memoria tm/en.json y regenerar.
const EPOCAS_FICHAS = {
 "ant": {
  "anos": "From the 6th century BC to the 5th century AD (by convention, until the fall of Rome in 476).",
  "abre": "<p>In the Greek cities of Ionia, such as Miletus, some thinkers begin to explain nature without turning to the gods: this is the step <strong>from myth to logos</strong>. According to Herodotus, Thales predicted a solar eclipse (that of 585 BC). Trade, contact with Egypt and Babylon, alphabetic writing and cities where no caste of priests controls knowledge all help.</p>",
  "social": "<p>Life revolves around the <strong>polis</strong>, the city-state. Only free men born there are citizens: women, resident foreigners (metics) and slaves are excluded. The leisure to think (<em>scholé</em>, from which comes ‘school’) rests to a large extent on slave labour. Boys are educated with the poems of Homer, and in the 5th century BC the sophists begin to charge for teaching public speaking.</p>\n<p>After Alexander, the centre of learning moves to <strong>Alexandria</strong>, with its Museum and its Library (3rd century BC), and later to Rome, where Greek philosophy becomes part of the education of the elites.</p>",
  "politico": "<p>The poleis are independent and often rivals. Athens develops <strong>democracy</strong> after the reforms of Cleisthenes (508 BC), defeats the Persians in the Persian Wars (490-479 BC) and loses the Peloponnesian War against Sparta (431-404 BC); shortly afterwards it sentences Socrates to death (399 BC).</p>\n<p>Alexander the Great creates an enormous empire (336-323 BC) that splits into Hellenistic kingdoms, and these end up absorbed by <strong>Rome</strong>, first a republic and then an empire (from 27 BC). In 380 Christianity becomes the official religion of the Empire, and in 476 the Western Roman Empire falls.</p>",
  "ciencia": "<p>The Greeks turn the calculating techniques of Egypt and Babylon into <strong>demonstrative mathematics</strong>: the Pythagoreans and, around 300 BC, Euclid’s <em>Elements</em>. Eratosthenes calculates the circumference of the Earth (3rd century BC); Aristarchus proposes that the Earth revolves around the Sun, although the model with the Earth at the centre, which Ptolemy systematises in the 2nd century, will prevail. Hippocratic medicine looks for natural causes of diseases, and Aristotle founds biology by observing animals.</p>\n<p>Technology, by contrast, advances little: with plentiful slave labour, there is scarcely any interest in saving effort with machines.</p>",
  "pensamiento": "<ul>\n<li><strong>Presocratics:</strong> they seek the <em>arkhé</em>, the first principle of nature (<em>physis</em>): water, air, numbers, atoms.</li>\n<li><strong>Turn towards the human being:</strong> the sophists debate whether laws are natural or conventional, and Socrates asks what justice and virtue are.</li>\n<li><strong>Great systems:</strong> Plato (the Forms) and Aristotle (form within things) organise all branches of knowledge.</li>\n<li><strong>Hellenistic schools:</strong> Cynics, Epicureans, Stoics and Sceptics ask, above all, how to live serenely in an uncertain world.</li>\n<li><strong>End of the period:</strong> the Neoplatonism of Plotinus and the encounter with Christianity. Tertullian asked what Athens had to do with Jerusalem; others, such as Augustine, will make Greek philosophy an ally.</li>\n</ul>",
  "rupturas": "<p>Ancient philosophy does not disappear: Christianity absorbs it and transforms it. Augustine of Hippo reads the faith through Platonic eyes. In 529 the Emperor Justinian bans pagans from teaching philosophy in Athens, and Greek learning lives on above all in Byzantium and, from the 8th century, in the Islamic world, where Aristotle is translated into Arabic and commented on for centuries.</p>",
  "trampa": "<p>‘The Greeks invented philosophy out of nothing.’ They drew on Egypt and Babylon, and they were not the only ones: in the same centuries the Buddha was teaching in India and Confucius in China. What was distinctive about the Greeks was turning rational, public debate into a method. And another trap: ancient philosophy is not just Plato and Aristotle, but almost twelve centuries of different schools.</p>"
 },
 "med": {
  "anos": "From the 5th century to the 15th century (on the department’s timeline, from 476 to 1492).",
  "abre": "<p>In 476 the Western Roman Empire falls. Amid the ruin of the cities, the <strong>Church</strong> becomes the institution that preserves writing, books and teaching. Augustine of Hippo, who dies in 430 while the Vandals besiege his city, leaves behind the great synthesis of Greek philosophy and Christian faith that will guide the following centuries.</p>",
  "social": "<p>It is a society of <strong>estates</strong>: around the year 1000 it was described as made up of those who pray, those who fight and those who work. Most people live in the countryside, subject to a lord (<strong>feudalism</strong>). Monasteries copy and keep the ancient books; convents are also one of the few places where women can study and write, like Hildegard of Bingen.</p>\n<p>From the 11th century cities and trade are reborn, and <strong>universities</strong> appear (Bologna, Paris, Oxford, Salamanca). The Black Death (1347-1351) kills an enormous part of the European population, perhaps a third.</p>",
  "politico": "<p>After Rome, the Germanic kingdoms arise; Charlemagne is crowned emperor in the year 800. To the east the <strong>Byzantine Empire</strong> continues, and from the 7th century Islam spreads from Arabia to the Iberian Peninsula (al-Andalus, from 711). Popes and emperors dispute for centuries who has the last word, and the Crusades (1096-1291) pit Christians against Muslims.</p>\n<p>The period closes with two dates: the fall of Constantinople to the Ottomans (1453) and, in 1492, the capture of Granada and Columbus’s arrival in America.</p>",
  "ciencia": "<p>In the <strong>Baghdad</strong> of the 8th-10th centuries, Aristotle, Euclid, Ptolemy and Galen are translated into Arabic. Al-Khwarizmi gives his name to <strong>algebra</strong> and to the algorithm; Avicenna writes the <em>Canon of Medicine</em>, studied in Europe for centuries. In the 12th and 13th centuries, in Toledo and elsewhere, this knowledge is translated into Latin, and Europe adopts Hindu-Arabic numerals and the zero.</p>\n<p>Technology advances more than is usually believed: the heavy plough, mills, the mechanical clock and, around 1450, Gutenberg’s <strong>printing press</strong> with movable type.</p>",
  "pensamiento": "<ul>\n<li><strong>Faith and reason:</strong> the great problem of the period is how to fit what is believed together with what is demonstrated.</li>\n<li><strong>Patristics:</strong> the Church Fathers, with Augustine at their head, think about the faith with Platonic tools.</li>\n<li><strong>Scholasticism:</strong> in the schools and universities, reasoning follows a rigorous method (reading, question, disputation). Anselm proposes his ontological argument; Thomas Aquinas reconciles Aristotle with the faith.</li>\n<li><strong>Philosophy in Arabic and in Hebrew:</strong> Avicenna, Averroes and Maimonides think about the same problems from within Islam and Judaism.</li>\n<li><strong>Universals:</strong> does ‘the human being’ exist in addition to each individual human being? Abelard and Ockham answer that they are names or concepts.</li>\n</ul>",
  "rupturas": "<p>In the 14th century, Ockham separates faith from reason: what is believed cannot be demonstrated, and the razor that bears his name cuts away unnecessary entities. The plague, the Western Schism (1378-1417), with two and even three popes at once, and the criticism of Scholasticism by the Italian humanists open the way to the Renaissance. The printing press will do the rest.</p>",
  "trampa": "<p>‘The Middle Ages were a dark age.’ The name was invented by the humanists to disparage them, but in that period universities were born, logic reached a very high level and half of ancient learning was translated. And no: medieval scholars did not believe the Earth was flat; its spherical shape was taught in the universities, for example with Sacrobosco’s <em>Treatise on the Sphere</em> (13th century).</p>"
 },
 "ren": {
  "anos": "From the mid-15th century to the end of the 16th century (on the department’s timeline, from 1492 to 1600).",
  "abre": "<p>Three novelties change the world in a few years: the <strong>printing press</strong> (around 1450), which multiplies books; the arrival in Italy of Greek scholars and manuscripts from Byzantium; and Columbus’s arrival in America (1492), which shows that the world known to the ancients was only a part.</p>",
  "social": "<p>The Italian cities, such as Florence or Venice, grow rich through trade and banking, and families such as the Medici pay artists and scholars (<strong>patronage</strong>). Printed books reach more people, and the figure of the humanist who lives by writing, teaching or advising princes appears.</p>\n<p>The conquest of America destroys entire societies and opens up the Atlantic trade in enslaved people. It also provokes a philosophical debate: at the Valladolid Debate (1550-1551), Bartolomé de las Casas and Juan Ginés de Sepúlveda argue over whether the indigenous peoples may be subjugated.</p>",
  "politico": "<p>The <strong>modern states</strong> take shape, with kings who concentrate power (the Catholic Monarchs, France, England). Italy, divided into small states, is a battlefield for the great powers: in that context Machiavelli writes <em>The Prince</em> (1513).</p>\n<p>In 1517 Luther publishes his 95 theses and the Protestant <strong>Reformation</strong> begins. Europe is divided along religious lines: wars of religion, the Peace of Augsburg (1555), which lets each prince choose the religion of his subjects, and the Catholic response of the Council of Trent (1545-1563).</p>",
  "ciencia": "<p>In 1543 two decisive books appear: Copernicus’s <em>On the Revolutions of the Heavenly Spheres</em>, which puts the Sun at the centre, and Vesalius’s anatomy, which corrects Galen on the basis of dissections. Leonardo da Vinci unites art, observation and engineering. The <strong>scientific revolution</strong> begins here and will culminate in the 17th century with Kepler, Galileo, Harvey and Newton.</p>",
  "pensamiento": "<ul>\n<li><strong>Humanism:</strong> a return to the classical texts in their original language and confidence in the dignity of the human being, capable of making himself (Pico della Mirandola, <em>Oration on the Dignity of Man</em>, 1486).</li>\n<li><strong>Criticism and tolerance:</strong> Erasmus mocks the abuses of his time in <em>The Praise of Folly</em> (1511) and defends an inward, peaceful religion.</li>\n<li><strong>Utopias:</strong> Thomas More (<em>Utopia</em>, 1516) and, later, Campanella imagine just societies in order to criticise real ones.</li>\n<li><strong>Political realism:</strong> Machiavelli separates politics from religious morality.</li>\n<li><strong>An infinite nature:</strong> Nicholas of Cusa and Giordano Bruno, burned by the Inquisition in 1600, conceive of a universe without limits.</li>\n</ul>",
  "rupturas": "<p>At the end of the 16th century the authority of the Church is divided and that of Aristotle is in question. Montaigne doubts almost everything. The question inherited by the modern period is where to find a secure foundation for knowledge: Francis Bacon proposes a method based on experience (<em>Novum Organum</em>, 1620) and Descartes one based on reason (<em>Discourse on Method</em>, 1637).</p>\n<p>In Illustrious Thinkers, Descartes appears in this period because the department’s timeline closes it in 1600 and he was born in 1596; but his work opens modern philosophy.</p>",
  "trampa": "<p>‘In the Renaissance science defeated religion.’ Copernicus was a canon of the Church, and Kepler and Galileo were believers. Moreover, alongside the new science, magic, astrology and alchemy flourished, and many humanists took them very seriously.</p>"
 },
 "mod": {
  "anos": "The 17th century (on the department’s timeline, modern philosophy runs from 1600 to 1800; the Enlightenment has its own sheet here).",
  "abre": "<p>The <strong>scientific revolution</strong> changes the way we know things. Galileo points his telescope at the sky (1610) and argues that the book of nature is written in the language of mathematics (<em>The Assayer</em>, 1623). With the authority of the ancients in crisis, Descartes seeks to start from scratch, from a truth that cannot be doubted (<em>Discourse on Method</em>, 1637).</p>",
  "social": "<p>It is a century of crisis: the <strong>Thirty Years’ War</strong> (1618-1648) devastates central Europe, and epidemics and bad harvests are frequent. The Netherlands, a commercial and relatively tolerant republic, take in persecuted or troublesome thinkers: Descartes and Spinoza lived there, the latter expelled by his Jewish community in 1656.</p>\n<p>The learned form a ‘republic of letters’ that exchanges letters across Europe, such as those of Descartes and Elisabeth of Bohemia, and the first <strong>scientific academies</strong> are born: the Royal Society of London (1660) and the Academy of Sciences in Paris (1666).</p>",
  "politico": "<p><strong>Absolutism</strong> triumphs: the king concentrates all power, like Louis XIV in France (reigned 1643-1715). The Peace of Westphalia (1648) organises Europe into sovereign states. England is the exception: a civil war (1642-1651) ends with the execution of King Charles I in 1649, and the Glorious Revolution (1688-1689) limits the power of the crown. Hobbes writes <em>Leviathan</em> (1651) after the war; Locke, his <em>Two Treatises of Government</em> (1689) after the revolution.</p>",
  "ciencia": "<p>Kepler discovers that the planets move in ellipses; Harvey demonstrates the circulation of the blood (1628); the microscope reveals an invisible world (Hooke, <em>Micrographia</em>, 1665). Newton and Leibniz independently invent <strong>infinitesimal calculus</strong>, and Newton unites the physics of the heavens and that of the Earth in a single law of gravity (1687).</p>\n<p>The dominant image is <strong>mechanism</strong>: the world works like a great clock, with parts that move by contact according to mathematical laws.</p>",
  "pensamiento": "<ul>\n<li><strong>Method and certainty:</strong> before knowing what there is, we must know how we can know it.</li>\n<li><strong>Rationalism:</strong> Descartes, Spinoza, Malebranche and Leibniz trust in ideas that reason knows by itself.</li>\n<li><strong>Empiricism:</strong> Locke and Berkeley hold that all knowledge comes from experience; Hume will take it to its limit in the following century.</li>\n<li><strong>Substance:</strong> how many are there? Two for Descartes (mind and matter), one for Spinoza, infinitely many monads for Leibniz, only matter for Hobbes.</li>\n<li><strong>Social contract and tolerance:</strong> Hobbes and Locke base power on a pact; Spinoza (1670) and Locke (1689) defend freedom of thought and religious tolerance.</li>\n</ul>",
  "rupturas": "<p>Newton and Locke become the models for the next generation: Voltaire makes them known in France in his <em>Letters on the English</em> (1734). The confidence in reason, which the 17th century applied above all to nature, the Enlightenment will extend to society, politics and religion.</p>",
  "trampa": "<p>‘Rationalists and empiricists were two opposing teams.’ The label was applied later by historians. They all read and answered one another: Locke argues with Descartes, and Leibniz devoted an entire book to replying to Locke (<em>New Essays on Human Understanding</em>). And almost all of them shared a confidence in mathematics and in the new physics.</p>"
 },
 "ilu": {
  "anos": "From the end of the 17th century (around 1680) to roughly 1800.",
  "abre": "<p>The scientific revolution culminates in Newton’s <em>Mathematical Principles of Natural Philosophy</em> (1687): the universe obeys laws that reason can discover. The following year, the English Glorious Revolution (1688-1689) subjects the king to a declaration of rights by Parliament. Reason and political freedom are the two ideas that the age will take furthest.</p>",
  "social": "<p>A <strong>bourgeoisie</strong> of merchants, doctors, lawyers and officials grows, which reads, debates and wants to have influence. Places for conversation appear outside the court and the Church: the <strong>cafés</strong>, the academies, the lodges and the <strong>salons</strong>, many run by women, like that of Madame Geoffrin in Paris. Newspapers and cheap books multiply, and something new appears: <strong>public opinion</strong>.</p>\n<p>But the Enlightenment was the affair of minorities: most of the population was rural and could not read. And the wealth of Europe’s ports depended to a large extent on the Atlantic trade in enslaved people.</p>",
  "politico": "<p>Almost all of Europe lives under <strong>absolute monarchies</strong>. Some kings adopt enlightened reforms without giving up power (so-called <strong>enlightened despotism</strong>: Frederick II of Prussia, Catherine II of Russia, Charles III in Spain). Censorship remains active: the <em>Encyclopédie</em> was banned in France in 1759 and went on being published in secret.</p>\n<p>At the end of the century, two revolutions bring the ideas into politics: the <strong>independence of the United States</strong> (1776), with its declaration of rights, and the <strong>French Revolution</strong> (1789), with the <em>Declaration of the Rights of Man and of the Citizen</em>.</p>",
  "ciencia": "<p>Newton becomes the model for all knowledge: observe, measure and look for laws. Linnaeus classifies living things (<em>Systema Naturae</em>, 1735); Lavoisier founds modern chemistry (<em>Elements of Chemistry</em>, 1789); Jenner demonstrates the first vaccine, against smallpox (1796). In Britain, Watt’s steam engine (patented in 1769) opens the <strong>Industrial Revolution</strong>.</p>\n<p>The <em>Encyclopédie</em> of Diderot and d'Alembert (1751-1772) aims to gather all knowledge, including that of the trades, with plates of workshops and machines: technical knowledge becomes worthy of philosophy.</p>",
  "pensamiento": "<p>The central idea was summed up by Kant in 1784: the Enlightenment is the human being’s emergence from a self-incurred immaturity; its motto, <em>sapere aude</em>, ‘Have courage to use your own understanding!’ (<em>An Answer to the Question: What Is Enlightenment?</em>). Hence its main features:</p>\n<ul>\n<li><strong>Critical reason:</strong> nothing is accepted on the basis of tradition or authority without being examined, not even reason itself (Hume, Kant).</li>\n<li><strong>Progress:</strong> knowledge and education can improve human life (Rousseau, <em>Emile</em>, 1762).</li>\n<li>Religious <strong>tolerance</strong> and criticism of superstition (Voltaire, <em>Treatise on Tolerance</em>, 1763). Many Enlightenment thinkers are deists: they believe in a creator God, but not in revealed religions.</li>\n<li><strong>Rights and separation of powers</strong> against absolutism (Montesquieu, <em>The Spirit of the Laws</em>, 1748; Rousseau, <em>The Social Contract</em>, 1762).</li>\n<li><strong>Happiness and utility:</strong> morality is conceived from sentiment (Hume) or from consequences (Bentham), and economics as a field of knowledge in its own right (Adam Smith, <em>The Wealth of Nations</em>, 1776).</li>\n<li>The first voices for <strong>the equality of women</strong>: Olympe de Gouges (1791) and Mary Wollstonecraft (1792).</li>\n</ul>",
  "rupturas": "<p>The Enlightenment does not end all at once. In Germany, Hamann and Herder reproach it for forgetting the feeling, the language and the history of each people, and <strong>Romanticism</strong> takes up that criticism. The Terror of the French Revolution (1793-1794) makes people ask whether reason can remake an entire society. Kant closes the period and examines it at the same time: his <em>Critiques</em> mark the limits of reason.</p>\n<p>Other lines continue into the 19th century: the <strong>utilitarianism</strong> and <strong>liberalism</strong> of Bentham and Mill (which is why in Illustrious Thinkers they are placed in this period), and the faith in progress, which Hegel and Marx inherit. In the 20th century, Adorno and Horkheimer (<em>Dialectic of Enlightenment</em>, 1944) ask why Enlightenment reason did not prevent barbarism.</p>",
  "trampa": "<p>‘The Enlightenment was French.’ Paris was its most visible capital, but there was a Scottish Enlightenment (Hume, Smith), a German one (Kant, Lessing, Mendelssohn), a Spanish one (Feijoo, Jovellanos) and an American one (Franklin, Jefferson). And ‘enlightened’ does not mean ‘atheist’: Holbach was one, but Voltaire was a deist and Kant defended a rational faith.</p>"
 },
 "con": {
  "nombre": "Contemporary period I: the 19th century",
  "block": "con",
  "nacidos": [
   1700,
   1849
  ],
  "temasHF": [
   21
  ],
  "anos": "From the end of the 18th century to the First World War (roughly 1800 to 1914).",
  "abre": "<p>The French Revolution and the Napoleonic wars change the political map of Europe, and the <strong>Industrial Revolution</strong> changes the way people live and work. In philosophy, Kant has left open the question of the limits of reason, and German idealism tries to overcome them: Hegel publishes the <em>Phenomenology of Spirit</em> in 1807.</p>",
  "social": "<p>Factories draw millions of people from the countryside into the cities. The <strong>proletariat</strong> is born, with extremely long working days and child labour, as Dickens’s novels describe, and with it the labour movement, trade unions and the socialisms: the so-called utopian ones (Owen, Fourier, Saint-Simon) and that of Marx and Engels (<em>The Communist Manifesto</em>, 1848). The bourgeoisie becomes the ruling class, and schools and the press reach ever wider sections of the population.</p>",
  "politico": "<p>It is the century of the liberal revolutions (1830, 1848), of constitutions and of <strong>nationalisms</strong>: Italy was unified in 1861 and Germany in 1871. The European powers divide up Africa and a good part of Asia into <strong>colonial empires</strong> (Berlin Conference, 1884-1885). Slavery is gradually abolished: in the British Empire in 1833, in the United States in 1865 after a civil war, in Spanish Cuba in 1886.</p>",
  "ciencia": "<p>Darwin explains the evolution of species by natural selection (<em>On the Origin of Species</em>, 1859) and Mendel discovers the laws of heredity (1866). Faraday and Maxwell unify electricity and magnetism; Pasteur shows the role of microbes in disease. The railway, the telegraph and electricity transform daily life. Boole and Frege begin to turn logic into a branch of mathematics.</p>",
  "pensamiento": "<ul>\n<li><strong>Idealism and Romanticism:</strong> Fichte, Schelling and Hegel think of reality as the unfolding of spirit; Novalis, Schlegel and Hölderlin champion feeling, art and the history of each people.</li>\n<li><strong>Positivism:</strong> Comte holds that knowledge culminates in positive science, based on observable facts.</li>\n<li><strong>Utilitarianism and liberalism:</strong> Mill defends individual freedom against the State and against the pressure of the majority (<em>On Liberty</em>, 1859).</li>\n<li><strong>Socialism and anarchism:</strong> Marx, Proudhon and Kropotkin criticise property and capitalism from different positions.</li>\n<li><strong>Suspicion:</strong> Marx and Nietzsche look behind ideas for economic interests or the will to power.</li>\n</ul>",
  "rupturas": "<p>The 19th century trusts in <strong>progress</strong>: the world’s fairs show ever more astonishing machines. But cracks are growing within it: Nietzsche announces the ‘death of God’ (1882), Freud explores an unconscious that reason does not control (<em>The Interpretation of Dreams</em>, 1900) and classical physics begins to totter (Einstein, 1905). The First World War (1914) shatters that confidence for good.</p>",
  "trampa": "<p>‘Contemporary means of today.’ In history, the Contemporary Age begins at the end of the 18th century: Hegel and Marx are ‘contemporary’ philosophers even though they lived two centuries ago. That is why on this site the period is divided into two profiles: the 19th century and the 20th and 21st centuries.</p>"
 },
 "con2": {
  "nombre": "Contemporary period II: the 20th and 21st centuries",
  "block": "con",
  "nacidos": [
   1850,
   2100
  ],
  "temasHF": [
   22,
   23,
   24,
   25,
   26,
   27
  ],
  "anos": "From the First World War (1914) to today.",
  "abre": "<p>The <strong>First World War</strong> (1914-1918), with millions dead in the trenches and weapons made in series, shatters the 19th century’s confidence in progress. In 1917, the Russian Revolution promises a classless society. The century begins by asking what went wrong in the civilisation that believed itself the most advanced.</p>",
  "social": "<p>The <strong>mass society</strong> arrives: big cities, consumption, cinema, radio and television. Women win the vote (in Spain, in 1931) and schooling reaches almost everyone. In the second half of the century the <strong>welfare state</strong> spreads across Europe, with public healthcare and pensions.</p>\n<p>Today we live in a <strong>globalised</strong> world connected by the internet, with enormous inequalities, great migrations and an ecological crisis that forces us to rethink progress.</p>",
  "politico": "<p>Between the two world wars <strong>totalitarianisms</strong> emerge (fascism, Nazism, Stalinism). The Second World War (1939-1945) ends with the Holocaust and with the atomic bombs of Hiroshima and Nagasaki. Afterwards the UN and the Universal Declaration of Human Rights (1948) are born, the Cold War begins, and Asia and Africa are decolonised.</p>\n<p>In Spain, the Francoist dictatorship (1939-1975) sends many thinkers into exile, such as María Zambrano. The fall of the Berlin Wall (1989) closes the Cold War; the 21st century brings the financial crisis of 2008, the covid-19 pandemic (2020) and new wars.</p>",
  "ciencia": "<p>Einstein (relativity) and quantum mechanics change the idea of space, time and matter. In 1953 the structure of DNA is described, with data from Rosalind Franklin. Turing (1936) and Shannon (1948) lay the foundations of computing. Nuclear energy, the journey to the Moon (1969), the internet and artificial intelligence show an enormous technical power, which forces us to ask about its limits.</p>",
  "pensamiento": "<ul>\n<li><strong>Psychoanalysis:</strong> Freud shows that we are not fully masters of our own minds.</li>\n<li><strong>Existence and phenomenology:</strong> Heidegger, Sartre, Beauvoir and Camus start from concrete existence, freedom and anguish.</li>\n<li><strong>Linguistic turn:</strong> Wittgenstein and analytic philosophy examine language; Popper and Kuhn, science.</li>\n<li><strong>Critical theory:</strong> the Frankfurt School (Horkheimer, Adorno, Habermas) analyses mass society.</li>\n<li><strong>Philosophy in Spain:</strong> Unamuno, Ortega and Zambrano; in Basque, Txillardegi and Azurmendi.</li>\n<li><strong>Debates today:</strong> feminism (Beauvoir, Butler), postmodernity (Lyotard, Foucault, Derrida), justice (Rawls), ecology (Yayo Herrero), technology and mind (Han, Bostrom, Chalmers).</li>\n</ul>",
  "rupturas": "<p>It is an era that has not ended, with several internal breaks. Auschwitz and Hiroshima force us to ask what reason has done (Adorno, Arendt); in 1979, Lyotard announces the end of the ‘grand narratives’. The questions open today, such as artificial intelligence, the climate crisis or disinformation, may already be opening another era that we do not yet know how to name.</p>",
  "trampa": "<p>‘In today’s philosophy anything goes.’ That there are many currents does not mean that any opinion will do: each argues with the others using reasons. And ‘postmodern’ is not an insult, nor does it mean ‘very modern’: it is a specific thesis about the end of the grand narratives, which also has critics, such as Habermas.</p>"
 }
};
